version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: teamflow_postgres
    restart: always
    environment:
      POSTGRES_USER: harrydunnie
      POSTGRES_PASSWORD: Superadmin#@$
      POSTGRES_DB: teamflow-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
